// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmxy3_R88XCixqn_p_SgLEPYoN2evwIgM',
    appId: '1:973539794559:web:394ba1e7038b9fd340294a',
    messagingSenderId: '973539794559',
    projectId: 'my-new-chat-app',
    authDomain: 'my-new-chat-app-43390.firebaseapp.com',
    databaseURL: 'https://my-new-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-new-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-qCoGo5wR9Bd9RVYiCgSchnAmJql6sE',
    appId: '1:973539794559:android:8a03fb1221b4b96a40294a',
    messagingSenderId: '973539794559',
    projectId: 'my-new-chat-app',
    databaseURL: 'https://my-new-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-new-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRlFTtZKZfPfErMTq6Aah9Z6SeQSm_mU',
    appId: '1:973539794559:ios:752279287111ed9b40294a',
    messagingSenderId: '973539794559',
    projectId: 'my-new-chat-app',
    databaseURL: 'https://my-new-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-new-chat-app.appspot.com',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQRlFTtZKZfPfErMTq6Aah9Z6SeQSm_mU',
    appId: '1:973539794559:ios:c3f7b20d19714b4b40294a',
    messagingSenderId: '973539794559',
    projectId: 'my-new-chat-app',
    databaseURL: 'https://my-new-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-new-chat-app.appspot.com',
    iosBundleId: 'com.example.chatapp2.RunnerTests',
  );
}
